@dataclass-style structured configs to @attrs-style
facebookresearch/habitat-lab pull request #1172
Opened 2023-03-01 18:41 UTC by rpartsey

## Motivation and Context

- Finish @dataclass-style structured configs to @attr.s-style @attr.s(auto_attribs=True, slots=True).
- Migrated code to modern attrs API

## How Has This Been Tested

## Types of changes

- Docs change / refactoring / dependency upgrade
- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have completed my CLA (see **CONTRIBUTING**)
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

2023-03-01 19:13 UTC, vincentpierre approved these changes
LGTM, did you do some testings to make sure we do not have issues with overwriting configs?

2023-03-01 19:55 UTC, Skylion007 commented on habitat-lab/habitat/datasets/rearrange/run_episode_generator.py
> +    scene_sets: List[Any] = []
I am against doing this as this technically bad behavior. I would rather we stick to dataclasses and wrap it with this: https://pypi.org/project/dataslots/

2023-03-01 19:57 UTC, Skylion007 requested changes
We should consider sticking with dataclasses. They are better supported and I don't see any performance gains from doing it here. The are some nice features like validators, but we aren't using them currently. One of the nice things about having these files as dataclasses is that we can define them without Hydra. Not having a attrs.Factory of fields initializer creates bugprone behavior since our default args are mutable.

2023-03-01 20:13 UTC, rpartsey commented
This PR can actually be decomposed into two: 
1.  structured config `@dataclass`-style definition to `@attr.s`-style definition (update code that wasn't updated in https://github.com/facebookresearch/habitat-lab/pull/1120)
2. migrating our code to modern attrs API (should still be valid)

2023-03-01 20:21 UTC, rpartsey commented
> LGTM, did you do some testings to make sure we do not have issues with overwriting configs?

I didn't observe anything during development if structured configs (parent and child) are defined the same style. Though, I didn't test extensively.

2023-03-02 17:09 UTC, Skylion007 commented on habitat-lab/habitat/datasets/rearrange/run_episode_generator.py
> +    scene_sets: List[Any] = []
The main issue here is that the list can be edited and it will affect the DEFAULT parameters of the config which is unexpected behavior and bugprone.

2023-03-03 13:01 UTC, rpartsey commented
Closing in favour of https://github.com/facebookresearch/habitat-lab/pull/1182.

2023-03-03 13:01 UTC, closed without merging